#!/usr/bin/env node
/**
 * Builds the Android app and puts it on the USB-attached phone, in one command:
 *
 *   npm run android                 web build → deploy to Vercel → Android app (TWA) → install
 *   npm run android -- --no-deploy  skip the web build and deploy (rebuild + reinstall the APK only)
 *   npm run android -- --no-install build the APK only (apps/android/dist/ar-mining-training.apk)
 *
 * The Android app is a Trusted Web Activity: a small native app, generated by Bubblewrap from
 * apps/android/twa-manifest.json, that opens the deployed web app full screen in Chrome's engine
 * (so WebXR AR keeps working). Chrome hides its address bar only when the site's
 * /.well-known/assetlinks.json names this app's signing key, which this script keeps in sync.
 *
 * First run: creates the signing key in apps/android/keys/ (gitignored; back it up — updates must
 * be signed with the same key) and links apps/mobile to the Vercel project `ar-mining-training`
 * (run `npx vercel login` first if asked).
 *
 * Env: ARMT_JDK=<JDK 17–23 home> (default: Android Studio's bundled JDK)
 *      ANDROID_HOME=<Android SDK>  ADB=<path to adb>  ANDROID_SERIAL=<device serial>
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { platform } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { connectPhone, fail, isListening, reversePorts, sdkCandidates } from './lib/adb.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MOBILE = path.join(ROOT, 'apps', 'mobile');
const ANDROID = path.join(ROOT, 'apps', 'android');
const TWA_MANIFEST = path.join(ANDROID, 'twa-manifest.json');
const KEYS = path.join(ANDROID, 'keys');
const KEYSTORE = path.join(KEYS, 'release.keystore');
const SIGNING = path.join(KEYS, 'signing.json');
const PROJECT = path.join(ANDROID, 'twa');
const APK = path.join(ANDROID, 'dist', 'ar-mining-training.apk');
const ASSET_LINKS = path.join(MOBILE, 'public', '.well-known', 'assetlinks.json');
const VERCEL = 'vercel@62';
const VERCEL_PROJECT = 'ar-mining-training';
const API_PORT = 8000;

const deploy = !process.argv.includes('--no-deploy');
const install = !process.argv.includes('--no-install');
const isWindows = platform() === 'win32';
const exe = (name) => (isWindows ? `${name}.exe` : name);

// @bubblewrap/core is a dependency of the apps/android workspace.
const bubblewrap = createRequire(path.join(ANDROID, 'package.json'))('@bubblewrap/core');

function step(title) {
  console.log(`\n▶ ${title}`);
}

/** Runs a command with live output; exits on failure. `shell` is needed for npm/npx on Windows. */
function exec(
  command,
  args,
  { cwd = ROOT, env = process.env, shell = false, capture = false } = {},
) {
  const result = shell
    ? spawnSync([command, ...args].join(' '), {
        cwd,
        env,
        shell: true,
        stdio: capture ? ['inherit', 'pipe', 'inherit'] : 'inherit',
        encoding: 'utf8',
      })
    : spawnSync(command, args, {
        cwd,
        env,
        stdio: capture ? ['inherit', 'pipe', 'inherit'] : 'inherit',
        encoding: 'utf8',
      });
  if (result.error) fail(`Could not run ${command}: ${result.error.message}`);
  if (result.status !== 0)
    fail(`\`${[command, ...args].join(' ')}\` failed (exit ${result.status}).`);
  return result.stdout ?? '';
}

function quiet(command, args, options = {}) {
  const result = spawnSync(command, args, { encoding: 'utf8', ...options });
  return { ok: result.status === 0, output: `${result.stdout ?? ''}${result.stderr ?? ''}` };
}

// ---- Toolchain -------------------------------------------------------------------------------

/** A JDK that can run the Gradle version in Bubblewrap's template (8.11: Java 17–23). */
function findJdk() {
  const candidates = [
    process.env.ARMT_JDK,
    isWindows && 'C:\\Program Files\\Android\\Android Studio\\jbr',
    platform() === 'darwin' && '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
    '/opt/android-studio/jbr',
    process.env.JAVA_HOME,
  ].filter(Boolean);
  for (const home of candidates) {
    const java = path.join(home, 'bin', exe('java'));
    if (!existsSync(java)) continue;
    const { output } = quiet(java, ['-version']);
    const major = Number(/version "(\d+)/.exec(output)?.[1]);
    if (major >= 17 && major <= 23) return home;
    console.log(`• Skipping JDK ${major} at ${home} (Gradle 8.11 needs 17–23)`);
  }
  fail('No suitable JDK (17–23) was found for the Android build.', [
    'Install Android Studio (it bundles JDK 21), or install JDK 21 (e.g. Eclipse Temurin 21).',
    'If it is somewhere else, set ARMT_JDK to its folder (the one containing bin/java).',
  ]);
}

function findSdk() {
  const home = sdkCandidates().find((dir) => existsSync(path.join(dir, 'build-tools')));
  if (home == null) {
    fail('The Android SDK was not found.', [
      'Install Android Studio and open it once (it installs the SDK), or install the command-line tools.',
      'Set ANDROID_HOME to the SDK folder if it is not in the default place.',
    ]);
  }
  // Newest build-tools that has apksigner.
  const buildTools = readdirSync(path.join(home, 'build-tools'))
    .filter((version) =>
      existsSync(path.join(home, 'build-tools', version, 'lib', 'apksigner.jar')),
    )
    .sort((a, b) => b.localeCompare(a, undefined, { numeric: true }))[0];
  if (buildTools == null) {
    fail('No Android build-tools found in the SDK.', [
      'Android Studio > Settings > Android SDK > SDK Tools: install "Android SDK Build-Tools".',
    ]);
  }
  return { home, buildTools: path.join(home, 'build-tools', buildTools) };
}

// ---- Signing key and Digital Asset Links ------------------------------------------------------

function ensureSigningKey(jdk, alias) {
  if (existsSync(KEYSTORE) && existsSync(SIGNING)) {
    return JSON.parse(readFileSync(SIGNING, 'utf8'));
  }
  if (existsSync(KEYSTORE)) {
    fail(`${KEYSTORE} exists but ${SIGNING} (its password) is missing.`, [
      'Restore signing.json from your backup, or delete the keystore to create a new key (the installed app must then be uninstalled once).',
    ]);
  }
  step('Creating the app signing key (first run)');
  mkdirSync(KEYS, { recursive: true });
  // PKCS12 keystores use one password for the store and the key.
  const password = randomBytes(24).toString('base64url');
  exec(
    path.join(jdk, 'bin', exe('keytool')),
    [
      '-genkeypair',
      '-keystore',
      KEYSTORE,
      '-storetype',
      'PKCS12',
      '-alias',
      alias,
      '-keyalg',
      'RSA',
      '-keysize',
      '2048',
      '-validity',
      '10000',
      '-storepass:env',
      'ARMT_KEYSTORE_PASSWORD',
      '-dname',
      'CN=AR Mining Training, O=SIH 2026, C=IN',
    ],
    { env: { ...process.env, ARMT_KEYSTORE_PASSWORD: password } },
  );
  const signing = { alias, password };
  writeFileSync(SIGNING, `${JSON.stringify(signing, null, 2)}\n`);
  console.log(
    `• Key saved in ${KEYS} (gitignored). Back this folder up: app updates must be signed with it.`,
  );
  return signing;
}

function signingFingerprint(jdk, signing) {
  const { output } = quiet(
    path.join(jdk, 'bin', exe('keytool')),
    [
      '-list',
      '-v',
      '-keystore',
      KEYSTORE,
      '-alias',
      signing.alias,
      '-storepass:env',
      'ARMT_KEYSTORE_PASSWORD',
    ],
    { env: { ...process.env, ARMT_KEYSTORE_PASSWORD: signing.password } },
  );
  const fingerprint = /SHA256:\s*([0-9A-F:]{95})/.exec(output)?.[1];
  if (fingerprint == null) fail('Could not read the signing key fingerprint.', [output.trim()]);
  return fingerprint;
}

function assetLinks(packageId, fingerprint) {
  const statement = [
    {
      relation: ['delegate_permission/common.handle_all_urls'],
      target: {
        namespace: 'android_app',
        package_name: packageId,
        sha256_cert_fingerprints: [fingerprint],
      },
    },
  ];
  return `${JSON.stringify(statement, null, 2)}\n`;
}

// ---- Web app: build and deploy ---------------------------------------------------------------

function writeVercelOutput() {
  const output = path.join(MOBILE, '.vercel', 'output');
  rmSync(output, { recursive: true, force: true });
  cpSync(path.join(MOBILE, 'dist'), path.join(output, 'static'), { recursive: true });
  const config = {
    version: 3,
    routes: [
      // The service worker must be re-checked on every visit so updates reach the phone.
      {
        src: '/(sw\\.js|registerSW\\.js|manifest\\.webmanifest)',
        headers: { 'cache-control': 'public, max-age=0, must-revalidate' },
        continue: true,
      },
      {
        src: '/assets/(.*)',
        headers: { 'cache-control': 'public, max-age=31536000, immutable' },
        continue: true,
      },
      {
        src: '/\\.well-known/assetlinks\\.json',
        headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=300' },
        continue: true,
      },
      { handle: 'filesystem' },
      // Single-page app: every other path serves the app shell.
      { src: '/(.*)', dest: '/index.html' },
    ],
  };
  writeFileSync(path.join(output, 'config.json'), `${JSON.stringify(config, null, 2)}\n`);
}

function deployToVercel() {
  const npx = (args, options = {}) =>
    exec('npx', ['--yes', VERCEL, ...args], { cwd: MOBILE, shell: true, ...options });
  const whoami = spawnSync(`npx --yes ${VERCEL} whoami`, {
    cwd: MOBILE,
    shell: true,
    encoding: 'utf8',
  });
  if (whoami.status !== 0) {
    fail('Not logged in to Vercel.', [
      'Run `npx vercel login` and approve the login in your browser.',
      'Run `npm run android` again.',
    ]);
  }
  if (!existsSync(path.join(MOBILE, '.vercel', 'project.json'))) {
    step(`Linking apps/mobile to the Vercel project "${VERCEL_PROJECT}"`);
    npx(['link', '--yes', '--project', VERCEL_PROJECT]);
  }
  writeVercelOutput();
  const stdout = npx(['deploy', '--prebuilt', '--prod', '--yes', '--format', 'json'], {
    capture: true,
  });
  const json = stdout.slice(stdout.indexOf('{'));
  let deployment;
  try {
    deployment = JSON.parse(json);
  } catch {
    fail('Could not read the Vercel deploy result.', [stdout.trim()]);
  }
  return deployment;
}

/** The stable production domain (the Android app is tied to it). */
function productionHost(deployment) {
  const aliases = [deployment.alias, deployment.aliases, deployment.deployment?.alias]
    .flat()
    .filter((alias) => typeof alias === 'string')
    .map((alias) => alias.replace(/^https?:\/\//, ''));
  return (
    aliases.find((alias) => alias === `${VERCEL_PROJECT}.vercel.app`) ??
    aliases.find((alias) => alias.endsWith('.vercel.app')) ??
    `${VERCEL_PROJECT}.vercel.app`
  );
}

async function checkAssetLinks(host, expected) {
  const url = `https://${host}/.well-known/assetlinks.json`;
  let response;
  try {
    response = await fetch(url, { signal: AbortSignal.timeout(15000) });
  } catch (error) {
    fail(`Could not fetch ${url}: ${error.message}`);
  }
  if (response.status === 401 || response.status === 403) {
    fail(`${url} is protected (HTTP ${response.status}).`, [
      `Vercel dashboard → ${VERCEL_PROJECT} → Settings → Deployment Protection: turn off "Vercel Authentication" for production.`,
      'Run `npm run android` again.',
    ]);
  }
  const body = await response.text();
  if (!response.ok || body.trim() !== expected.trim()) {
    fail(`${url} does not match the app's signing key (HTTP ${response.status}).`, [
      'Chrome would show its address bar. Re-run `npm run android` to redeploy.',
    ]);
  }
  console.log(`• ${url} matches the signing key`);
}

// ---- Android app ------------------------------------------------------------------------------

/** Always increasing, so `adb install -r` accepts every new build (minutes since 2026-01-01). */
function versionCode() {
  return Math.floor((Date.now() - Date.UTC(2026, 0, 1)) / 60_000);
}

async function generateProject(manifest) {
  // Regenerate the sources from twa-manifest.json; keep Gradle's caches for speed.
  rmSync(path.join(PROJECT, 'app', 'src'), { recursive: true, force: true });
  const log = new bubblewrap.ConsoleLog('bubblewrap');
  await new bubblewrap.TwaGenerator().createTwaProject(PROJECT, manifest, log);
}

function buildApk({ jdk, sdk, signing }) {
  const env = {
    ...process.env,
    JAVA_HOME: jdk,
    ANDROID_HOME: sdk.home,
    ANDROID_SDK_ROOT: sdk.home,
  };
  // --no-daemon: don't leave a ~1 GB Gradle process running after the build.
  // Absolute path: Windows may be set not to run programs from the current folder.
  exec(
    isWindows ? `"${path.join(PROJECT, 'gradlew.bat')}"` : path.join(PROJECT, 'gradlew'),
    ['assembleRelease', '--no-daemon', '--console=plain', '--warning-mode=none'],
    {
      cwd: PROJECT,
      env,
      shell: isWindows,
    },
  );
  const outputs = path.join(PROJECT, 'app', 'build', 'outputs', 'apk', 'release');
  const unsigned = path.join(outputs, 'app-release-unsigned.apk');
  const aligned = path.join(outputs, 'app-release-aligned.apk');
  exec(path.join(sdk.buildTools, exe('zipalign')), ['-f', '-p', '4', unsigned, aligned]);
  mkdirSync(path.dirname(APK), { recursive: true });
  exec(
    path.join(jdk, 'bin', exe('java')),
    [
      '-jar',
      path.join(sdk.buildTools, 'lib', 'apksigner.jar'),
      'sign',
      '--ks',
      KEYSTORE,
      '--ks-key-alias',
      signing.alias,
      '--ks-pass',
      'env:ARMT_KEYSTORE_PASSWORD',
      '--key-pass',
      'env:ARMT_KEYSTORE_PASSWORD',
      '--out',
      APK,
      aligned,
    ],
    { env: { ...env, ARMT_KEYSTORE_PASSWORD: signing.password } },
  );
}

function installOnPhone(packageId) {
  const { adb } = connectPhone('npm run android');
  let result = adb(['install', '-r', APK]);
  if (!result.ok && /INSTALL_FAILED_UPDATE_INCOMPATIBLE/.test(result.output)) {
    // Installed copy was signed with a different key (e.g. a new keystore): replace it.
    console.log('• Installed app has a different signing key; uninstalling it first');
    adb(['uninstall', packageId]);
    result = adb(['install', '-r', APK]);
  }
  if (!result.ok) fail('adb install failed.', [result.output]);
  console.log(`• Installed ${path.relative(ROOT, APK)}`);
  // The app's login API runs on this laptop; the phone reaches it as http://localhost:8000.
  reversePorts(adb, [API_PORT]);
  adb(['shell', 'am', 'force-stop', packageId]);
  const launch = adb(['shell', 'am', 'start', '-n', `${packageId}/.LauncherActivity`]);
  if (!launch.ok || /Error/.test(launch.output)) fail('Could not start the app.', [launch.output]);
  console.log('• Started "AR Mining Training" on the phone');
}

// ---- Main -------------------------------------------------------------------------------------

const manifest = await bubblewrap.TwaManifest.fromFile(TWA_MANIFEST);
const jdk = findJdk();
const sdk = findSdk();
console.log(
  `• JDK: ${jdk}\n• Android SDK: ${sdk.home} (build-tools ${path.basename(sdk.buildTools)})`,
);

const signing = ensureSigningKey(jdk, manifest.signingKey.alias);
const fingerprint = signingFingerprint(jdk, signing);
const statement = assetLinks(manifest.packageId, fingerprint);
console.log(`• Signing key SHA-256: ${fingerprint}`);
if (!existsSync(ASSET_LINKS) || readFileSync(ASSET_LINKS, 'utf8') !== statement) {
  mkdirSync(path.dirname(ASSET_LINKS), { recursive: true });
  writeFileSync(ASSET_LINKS, statement);
  console.log(`• Updated ${path.relative(ROOT, ASSET_LINKS)} (commit it)`);
}

if (deploy) {
  step('Building the web app');
  exec('npm', ['run', 'build', '-w', '@ar-training/mobile'], { shell: true });
  step('Deploying to Vercel (production)');
  const host = productionHost(deployToVercel());
  console.log(`• Live at https://${host}`);
  if (host !== manifest.host) {
    // The Android app is tied to one domain: keep twa-manifest.json pointing at it.
    const json = JSON.parse(readFileSync(TWA_MANIFEST, 'utf8'));
    json.host = host;
    json.iconUrl = `https://${host}/pwa-512x512.png`;
    json.maskableIconUrl = `https://${host}/maskable-icon-512x512.png`;
    writeFileSync(TWA_MANIFEST, `${JSON.stringify(json, null, 2)}\n`);
    Object.assign(manifest, { host, iconUrl: json.iconUrl, maskableIconUrl: json.maskableIconUrl });
    console.log(`• Updated ${path.relative(ROOT, TWA_MANIFEST)} host → ${host} (commit it)`);
  }
}
await checkAssetLinks(manifest.host, statement);

step(`Generating the Android project with Bubblewrap (https://${manifest.host})`);
manifest.appVersionCode = versionCode();
manifest.signingKey = { path: KEYSTORE, alias: signing.alias };
manifest.fingerprints = [{ name: 'release', value: fingerprint }];
await generateProject(manifest);

step(`Building and signing the APK (versionCode ${manifest.appVersionCode})`);
buildApk({ jdk, sdk, signing });
console.log(`• Signed APK: ${path.relative(ROOT, APK)}`);

if (install) {
  step('Installing on the phone');
  installOnPhone(manifest.packageId);
  if (!(await isListening(API_PORT))) {
    console.warn(
      '! The API is not running: first login on the phone needs `npm run dev:api` on this laptop.',
    );
  }
}

console.log(
  install
    ? `
✔ Done. "AR Mining Training" opens full screen from the phone's app drawer.
  Web updates: \`npm run android\` again (or just redeploy; the app loads the live site).
`
    : `
✔ Done. Install it with: adb install -r ${path.relative(ROOT, APK)}
`,
);
