#!/usr/bin/env node
/**
 * Builds the Android app and puts it on the USB-attached phone, in one command:
 *
 *   npm run android                 web build → deploy to Vercel → Android app (TWA) → install
 *   npm run android -- --no-deploy  skip the web build and deploy (rebuild + reinstall the APK only)
 *   npm run android -- --no-install build the APK only (apps/android/dist/ar-mining-training.apk)
 *
 * The Android app is a Trusted Web Activity: a small native app, generated by Bubblewrap from
 * apps/android/twa-manifest.json, that opens the deployed web app full screen in Chrome's engine
 * (so WebXR AR keeps working). Chrome hides its address bar only when the site's
 * /.well-known/assetlinks.json names this app's signing key, which this script keeps in sync.
 *
 * The web app is built against the hosted API (services/api/vercel/deployment.json, written by
 * `npm run deploy:api`), so the installed app needs no laptop. Without a hosted API it falls back
 * to the laptop's API at http://localhost:8000 through `adb reverse` (USB cable).
 *
 * First run: creates the signing key in apps/android/keys/ (gitignored; back it up — updates must
 * be signed with the same key) and links apps/mobile to the Vercel project `ar-mining-training`
 * (run `npx vercel login` first if asked).
 *
 * Env: ARMT_JDK=<JDK 17–23 home> (default: Android Studio's bundled JDK)
 *      ANDROID_HOME=<Android SDK>  ADB=<path to adb>  ANDROID_SERIAL=<device serial>
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { connectPhone, fail, isListening, reversePorts } from './lib/adb.mjs';
import {
  ensureSigningKey,
  exe,
  exec,
  findJdk,
  findSdk,
  gradle,
  installApk,
  KEYSTORE,
  quiet,
  ROOT,
  signApk,
  step,
  versionCode,
} from './lib/android-build.mjs';
import {
  deployProduction,
  ensureVercelLogin,
  hostedApiUrl,
  productionHost,
  vercel,
} from './lib/vercel.mjs';

const MOBILE = path.join(ROOT, 'apps', 'mobile');
const ANDROID = path.join(ROOT, 'apps', 'android');
const TWA_MANIFEST = path.join(ANDROID, 'twa-manifest.json');
const PROJECT = path.join(ANDROID, 'twa');
const APK = path.join(ANDROID, 'dist', 'ar-mining-training.apk');
const ASSET_LINKS = path.join(MOBILE, 'public', '.well-known', 'assetlinks.json');
const VERCEL_PROJECT = 'ar-mining-training';
const API_PORT = 8000;
const LOCAL_API = `http://localhost:${API_PORT}`;

const deploy = !process.argv.includes('--no-deploy');
const install = !process.argv.includes('--no-install');

// @bubblewrap/core is a dependency of the apps/android workspace.
const bubblewrap = createRequire(path.join(ANDROID, 'package.json'))('@bubblewrap/core');

// ---- Signing key and Digital Asset Links ------------------------------------------------------

function signingFingerprint(jdk, signing) {
  const { output } = quiet(
    path.join(jdk, 'bin', exe('keytool')),
    [
      '-list',
      '-v',
      '-keystore',
      KEYSTORE,
      '-alias',
      signing.alias,
      '-storepass:env',
      'ARMT_KEYSTORE_PASSWORD',
    ],
    { env: { ...process.env, ARMT_KEYSTORE_PASSWORD: signing.password } },
  );
  const fingerprint = /SHA256:\s*([0-9A-F:]{95})/.exec(output)?.[1];
  if (fingerprint == null) fail('Could not read the signing key fingerprint.', [output.trim()]);
  return fingerprint;
}

function assetLinks(packageId, fingerprint) {
  const statement = [
    {
      relation: ['delegate_permission/common.handle_all_urls'],
      target: {
        namespace: 'android_app',
        package_name: packageId,
        sha256_cert_fingerprints: [fingerprint],
      },
    },
  ];
  return `${JSON.stringify(statement, null, 2)}\n`;
}

// ---- Web app: build and deploy ---------------------------------------------------------------

function writeVercelOutput() {
  const output = path.join(MOBILE, '.vercel', 'output');
  rmSync(output, { recursive: true, force: true });
  cpSync(path.join(MOBILE, 'dist'), path.join(output, 'static'), { recursive: true });
  const config = {
    version: 3,
    routes: [
      // The service worker must be re-checked on every visit so updates reach the phone.
      {
        src: '/(sw\\.js|registerSW\\.js|manifest\\.webmanifest)',
        headers: { 'cache-control': 'public, max-age=0, must-revalidate' },
        continue: true,
      },
      {
        src: '/assets/(.*)',
        headers: { 'cache-control': 'public, max-age=31536000, immutable' },
        continue: true,
      },
      {
        src: '/\\.well-known/assetlinks\\.json',
        headers: { 'content-type': 'application/json', 'cache-control': 'public, max-age=300' },
        continue: true,
      },
      { handle: 'filesystem' },
      // Single-page app: every other path serves the app shell.
      { src: '/(.*)', dest: '/index.html' },
    ],
  };
  writeFileSync(path.join(output, 'config.json'), `${JSON.stringify(config, null, 2)}\n`);
}

function deployToVercel() {
  ensureVercelLogin(MOBILE, 'npm run android');
  if (!existsSync(path.join(MOBILE, '.vercel', 'project.json'))) {
    step(`Linking apps/mobile to the Vercel project "${VERCEL_PROJECT}"`);
    vercel(['link', '--yes', '--project', VERCEL_PROJECT], { cwd: MOBILE });
  }
  writeVercelOutput();
  return deployProduction(MOBILE, ['--prebuilt']);
}

async function checkAssetLinks(host, expected) {
  const url = `https://${host}/.well-known/assetlinks.json`;
  let response;
  try {
    response = await fetch(url, { signal: AbortSignal.timeout(15000) });
  } catch (error) {
    fail(`Could not fetch ${url}: ${error.message}`);
  }
  if (response.status === 401 || response.status === 403) {
    fail(`${url} is protected (HTTP ${response.status}).`, [
      `Vercel dashboard → ${VERCEL_PROJECT} → Settings → Deployment Protection: turn off "Vercel Authentication" for production.`,
      'Run `npm run android` again.',
    ]);
  }
  const body = await response.text();
  if (!response.ok || body.trim() !== expected.trim()) {
    fail(`${url} does not match the app's signing key (HTTP ${response.status}).`, [
      'Chrome would show its address bar. Re-run `npm run android` to redeploy.',
    ]);
  }
  console.log(`• ${url} matches the signing key`);
}

// ---- Android app ------------------------------------------------------------------------------

async function generateProject(manifest) {
  // Regenerate the sources from twa-manifest.json; keep Gradle's caches for speed.
  rmSync(path.join(PROJECT, 'app', 'src'), { recursive: true, force: true });
  const log = new bubblewrap.ConsoleLog('bubblewrap');
  await new bubblewrap.TwaGenerator().createTwaProject(PROJECT, manifest, log);
}

function buildApk({ jdk, sdk, signing }) {
  gradle(PROJECT, 'assembleRelease', { jdk, sdk });
  const outputs = path.join(PROJECT, 'app', 'build', 'outputs', 'apk', 'release');
  signApk({
    jdk,
    sdk,
    signing,
    unsigned: path.join(outputs, 'app-release-unsigned.apk'),
    out: APK,
  });
}

function installOnPhone(packageId, apiUrl) {
  const { adb } = connectPhone('npm run android');
  installApk(adb, APK, packageId);
  // Without a hosted API the app's API runs on this laptop, reached as http://localhost:8000.
  if (apiUrl === LOCAL_API) reversePorts(adb, [API_PORT]);
  adb(['shell', 'am', 'force-stop', packageId]);
  const launch = adb(['shell', 'am', 'start', '-n', `${packageId}/.LauncherActivity`]);
  if (!launch.ok || /Error/.test(launch.output)) fail('Could not start the app.', [launch.output]);
  console.log('• Started "AR Mining Training" on the phone');
}

// ---- Main -------------------------------------------------------------------------------------

const manifest = await bubblewrap.TwaManifest.fromFile(TWA_MANIFEST);
const jdk = findJdk();
const sdk = findSdk();
console.log(
  `• JDK: ${jdk}\n• Android SDK: ${sdk.home} (build-tools ${path.basename(sdk.buildTools)})`,
);

const signing = ensureSigningKey(jdk, manifest.signingKey.alias);
const fingerprint = signingFingerprint(jdk, signing);
const statement = assetLinks(manifest.packageId, fingerprint);
console.log(`• Signing key SHA-256: ${fingerprint}`);
if (!existsSync(ASSET_LINKS) || readFileSync(ASSET_LINKS, 'utf8') !== statement) {
  mkdirSync(path.dirname(ASSET_LINKS), { recursive: true });
  writeFileSync(ASSET_LINKS, statement);
  console.log(`• Updated ${path.relative(ROOT, ASSET_LINKS)} (commit it)`);
}

const apiUrl = hostedApiUrl() ?? LOCAL_API;
if (deploy) {
  step(`Building the web app (API: ${apiUrl})`);
  if (apiUrl === LOCAL_API) {
    console.warn(
      '! No hosted API yet (`npm run deploy:api`): the app will need the laptop API over USB.',
    );
  }
  exec('npm', ['run', 'build', '-w', '@ar-training/mobile'], {
    shell: true,
    env: { ...process.env, VITE_API_BASE_URL: apiUrl },
  });
  step('Deploying to Vercel (production)');
  const host = productionHost(deployToVercel(), VERCEL_PROJECT);
  console.log(`• Live at https://${host}`);
  if (host !== manifest.host) {
    // The Android app is tied to one domain: keep twa-manifest.json pointing at it.
    // Host, icon and shortcut URLs all move to the new domain.
    const json = readFileSync(TWA_MANIFEST, 'utf8')
      .replaceAll(`https://${manifest.host}/`, `https://${host}/`)
      .replace(`"host": "${manifest.host}"`, `"host": "${host}"`);
    writeFileSync(TWA_MANIFEST, json);
    Object.assign(manifest, await bubblewrap.TwaManifest.fromFile(TWA_MANIFEST));
    console.log(`• Updated ${path.relative(ROOT, TWA_MANIFEST)} host → ${host} (commit it)`);
  }
}
await checkAssetLinks(manifest.host, statement);

step(`Generating the Android project with Bubblewrap (https://${manifest.host})`);
manifest.appVersionCode = versionCode();
manifest.signingKey = { path: KEYSTORE, alias: signing.alias };
manifest.fingerprints = [{ name: 'release', value: fingerprint }];
await generateProject(manifest);

step(`Building and signing the APK (versionCode ${manifest.appVersionCode})`);
buildApk({ jdk, sdk, signing });
console.log(`• Signed APK: ${path.relative(ROOT, APK)}`);

if (install) {
  step('Installing on the phone');
  installOnPhone(manifest.packageId, apiUrl);
  if (apiUrl === LOCAL_API && !(await isListening(API_PORT))) {
    console.warn(
      '! The API is not running: first login on the phone needs `npm run dev:api` on this laptop.',
    );
  }
}

console.log(
  install
    ? `
✔ Done. "AR Mining Training" opens full screen from the phone's app drawer.
  Web updates: \`npm run android\` again (or just redeploy; the app loads the live site).
`
    : `
✔ Done. Install it with: adb install -r ${path.relative(ROOT, APK)}
`,
);
